/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package launcher;

import javax.swing.JLabel;

/**
 *
 * @author Sergio Tark
 */
public class Game extends javax.swing.JPanel {
 
    private int indiceImagenActual = 0;
    private String[] rutaImagenes;
    private int indexEscudo;
    private int indexSimulador;
    
    
   
    
    
 
    public Game(int indexEscudo, int indexSimulador) {
        
        this.indexEscudo = indexEscudo;
        this.indexSimulador = indexSimulador;
        
        initComponents();
        cargarImagenes();
        updateImage();
        actualizarTitulo();
        actualizarDescripción();
       
        
        //Listener para la flecha izq
        flechaIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            
            
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt){
                imagenAnterior();
            }
            
        });
        //Listener para la flecha dcha
        flechaDcha.addMouseListener(new java.awt.event.MouseAdapter() {
            
           
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt){
                imagenSiguiente();
            }
        });
        actualizarCirculos();
        
    }
    
        //Metodo para cargar las imagenes mediante el archivoJSON
        private void cargarImagenes() {
            
            int totalImagenes = 5;
            rutaImagenes = new String [totalImagenes];
            
            rutaImagenes = ManejoJSON.ImagenSimulador(indexEscudo, indexSimulador).split(",");
        
        
        }
    
        
        //Metodo para hacer el update de las imagenes
        private void updateImage(){
            if (rutaImagenes != null && rutaImagenes.length > 0){
                String rutaActual = rutaImagenes[indiceImagenActual];
                 panelSimulador.setIcon(new javax.swing.ImageIcon(rutaActual));
            }
          
        }
       //Metodo para mostrar la imagen anterior 
        private void imagenAnterior() {
        
            indiceImagenActual = (indiceImagenActual - 1 + rutaImagenes.length) % rutaImagenes.length;
            updateImage();
            actualizarCirculos();
        }
        //Metodo para mostrar la imagen siguiente
        private void imagenSiguiente() {
        
        
            indiceImagenActual = (indiceImagenActual + 1) % rutaImagenes.length;
            updateImage();
            actualizarCirculos();
        }
        //Metodo para actualizar los circulos del indice
        private void actualizarCirculos() {
        
            //Rutas de iconos
            String iconoRelleno = "/circulos/img/PuntoCarruselFilled.png";
            String iconoVacio = "/circulos/img/PuntoCarruselEmpty.png";
            
            //Array para los circulo
            JLabel[] circulos = {circulo1, circulo2, circulo3, circulo4, circulo5};
            
            for (int i = 0; i < circulos.length; i++){
                if (i == indiceImagenActual) {circulos[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(iconoRelleno)));}
                else {
                    circulos[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(iconoVacio)));
                }
                }
            
        }
        //Método para updatear el titulo
        private void actualizarTitulo() {
            String titulo = ManejoJSON.TituloGeneralSimulador(indexEscudo, indexSimulador);
            
            
            Titulo.setText(titulo);
           
        
        }
        //Método para updatear la descripción
        private void actualizarDescripción() {
            String descripcion = ManejoJSON.DescripcionSimulador(indexEscudo, indexSimulador);
            
             Descripcion.setText(descripcion);
        
        
        }
        
        
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSimulador = new javax.swing.JLabel();
        flechaIzq = new javax.swing.JLabel();
        flechaDcha = new javax.swing.JLabel();
        comenzar = new javax.swing.JLabel();
        circulo1 = new javax.swing.JLabel();
        circulo2 = new javax.swing.JLabel();
        circulo3 = new javax.swing.JLabel();
        circulo4 = new javax.swing.JLabel();
        circulo5 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Barra = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSimulador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelSimulador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Embarque/img/Embarque0.png"))); // NOI18N
        add(panelSimulador, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 870, 490));

        flechaIzq.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        flechaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flechas/img/Flecha izquierda.png"))); // NOI18N
        flechaIzq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(flechaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 40, 40));

        flechaDcha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        flechaDcha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flechas/img/Flecha derecha.png"))); // NOI18N
        flechaDcha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(flechaDcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 240, 40, 50));

        comenzar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        comenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Comenzar.png"))); // NOI18N
        comenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 700, -1, -1));

        circulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselFilled.png"))); // NOI18N
        add(circulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, -1));

        circulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselEmpty.png"))); // NOI18N
        circulo2.setPreferredSize(new java.awt.Dimension(15, 15));
        add(circulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));

        circulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselEmpty.png"))); // NOI18N
        circulo3.setPreferredSize(new java.awt.Dimension(15, 15));
        add(circulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        circulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselEmpty.png"))); // NOI18N
        circulo4.setPreferredSize(new java.awt.Dimension(15, 15));
        add(circulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, -1, -1));

        circulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselEmpty.png"))); // NOI18N
        circulo5.setMaximumSize(new java.awt.Dimension(15, 15));
        circulo5.setMinimumSize(new java.awt.Dimension(15, 15));
        circulo5.setPreferredSize(new java.awt.Dimension(15, 15));
        add(circulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, -1, -1));

        Titulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 340, 30));

        Barra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Barrita aislada descripción.png"))); // NOI18N
        add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, 30));

        Fondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/img/Cuadrado fondo enfocado.png"))); // NOI18N
        add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 56, 910, 460));

        Fondo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/img/Cuadrado fondo enfocado.png"))); // NOI18N
        add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 750, 460));

        Descripcion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(255, 255, 255));
        Descripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 1050, 100));

        jToggleButton1.setText("jToggleButton1");
        add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barra;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel circulo1;
    private javax.swing.JLabel circulo2;
    private javax.swing.JLabel circulo3;
    private javax.swing.JLabel circulo4;
    private javax.swing.JLabel circulo5;
    private javax.swing.JLabel comenzar;
    private javax.swing.JLabel flechaDcha;
    private javax.swing.JLabel flechaIzq;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel panelSimulador;
    // End of variables declaration//GEN-END:variables
}
