/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package launcher;

import javax.swing.JLabel;

/**
 *
 * @author Sergio Tark
 */
public class Game extends javax.swing.JPanel {
 
    private int indiceImagenActual = 0;
    private final String[] rutaImagenes = {
        "/Embarque/img/Embarque0.png",
        "/Embarque/img/Embarque1.png",
        "/Embarque/img/Embarque2.png",
        "/Embarque/img/Embarque3.png",
        "/Embarque/img/Embarque4.png"
    };
   
    
    
 
    public Game() {
       
        initComponents();
        
       
        
        
        flechaIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            
            
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt){
                imagenAnterior();
            }
            
        });
        
        flechaDcha.addMouseListener(new java.awt.event.MouseAdapter() {
            
           
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt){
                imagenSiguiente();
            }
        });
        actualizarCirculos();
        
    }
    
   
    
        private void updateImage(){
            panelSimulador.setIcon(new javax.swing.ImageIcon(getClass().getResource(rutaImagenes[indiceImagenActual])));
          
        }
        
        private void imagenAnterior() {
        
            indiceImagenActual = (indiceImagenActual - 1 + rutaImagenes.length) % rutaImagenes.length;
            updateImage();
            actualizarCirculos();
        }
        
        private void imagenSiguiente() {
        
        
            indiceImagenActual = (indiceImagenActual + 1) % rutaImagenes.length;
            updateImage();
            actualizarCirculos();
        }
        
        private void actualizarCirculos() {
        
            //Rutas de iconos
            String iconoRelleno = "/circulos/img/PuntoCarruselFilled.png";
            String iconoVacio = "/circulos/img/PuntoCarruselEmpty.png";
            
            //Array para los circulo
            JLabel[] circulos = {circulo1, circulo2, circulo3, ciruclo4, circulo5};
            
            for (int i = 0; i < circulos.length; i++){
                if (i == indiceImagenActual) {circulos[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(iconoRelleno)));}
                else {
                    circulos[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(iconoVacio)));
                }
                }
            
        }
        
        
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSimulador = new javax.swing.JLabel();
        flechaIzq = new javax.swing.JLabel();
        flechaDcha = new javax.swing.JLabel();
        comenzar = new javax.swing.JLabel();
        circulo1 = new javax.swing.JLabel();
        circulo2 = new javax.swing.JLabel();
        circulo3 = new javax.swing.JLabel();
        ciruclo4 = new javax.swing.JLabel();
        circulo5 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Barra = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSimulador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelSimulador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Embarque/img/Embarque0.png"))); // NOI18N
        add(panelSimulador, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 870, 490));

        flechaIzq.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        flechaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flechas/img/Flecha izquierda.png"))); // NOI18N
        flechaIzq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(flechaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 40, 40));

        flechaDcha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        flechaDcha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flechas/img/Flecha derecha.png"))); // NOI18N
        flechaDcha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(flechaDcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 240, 40, 50));

        comenzar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        comenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Comenzar.png"))); // NOI18N
        comenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 700, -1, -1));

        circulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselFilled.png"))); // NOI18N
        add(circulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, -1));

        circulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselEmpty.png"))); // NOI18N
        circulo2.setPreferredSize(new java.awt.Dimension(15, 15));
        add(circulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));

        circulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselEmpty.png"))); // NOI18N
        circulo3.setPreferredSize(new java.awt.Dimension(15, 15));
        add(circulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        ciruclo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ciruclo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselEmpty.png"))); // NOI18N
        ciruclo4.setPreferredSize(new java.awt.Dimension(15, 15));
        add(ciruclo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, -1, -1));

        circulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulos/img/PuntoCarruselEmpty.png"))); // NOI18N
        circulo5.setMaximumSize(new java.awt.Dimension(15, 15));
        circulo5.setMinimumSize(new java.awt.Dimension(15, 15));
        circulo5.setPreferredSize(new java.awt.Dimension(15, 15));
        add(circulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, -1, -1));

        Titulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Titulo.setText("Embarque y desembarque en helicoptero ");
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 340, 30));

        Barra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Barrita aislada descripción.png"))); // NOI18N
        add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, 30));

        Fondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/img/Cuadrado fondo enfocado.png"))); // NOI18N
        add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 56, 910, 460));

        Fondo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/img/Cuadrado fondo enfocado.png"))); // NOI18N
        add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 750, 460));

        Descripcion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(255, 255, 255));
        Descripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Descripcion.setText("⦁En un campo de prácticas sumido en el desorden y la confusión tienes que encontrar tienes que encontrar y colocar las partes de los EPIs utilizados en la extinción de incendios forestales.\n");
        add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 1050, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barra;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel circulo1;
    private javax.swing.JLabel circulo2;
    private javax.swing.JLabel circulo3;
    private javax.swing.JLabel circulo5;
    private javax.swing.JLabel ciruclo4;
    private javax.swing.JLabel comenzar;
    private javax.swing.JLabel flechaDcha;
    private javax.swing.JLabel flechaIzq;
    private javax.swing.JLabel panelSimulador;
    // End of variables declaration//GEN-END:variables
}
