/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package launcher;

import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author Sergio Tark
 */
public class Simuladores extends javax.swing.JPanel {

    public Home padre;
    
    
    public int grado;
   



//Constructor
    
    public Simuladores(int indexGrado) {
        initComponents();
        
        grado = indexGrado;
         JLabel[] grados = {
            grado0, grado1, grado2, grado3, grado4, grado5
        };
        //Bucle para el manejo de las miniauturas desde JSON
        for (int e = 0; e < grados.length; e++) {
           String ruta = ManejoJSON.MiniaturaSimulador(indexGrado, e);
            
            Tools.SetImageLabel(grados[e], ruta, new Dimension(381,291));
            
            JLabel simuladores = grados [e];
            
            int indexJuego = e;
            
             //Para resaltar las miniaturas cuando pasa el cursor
            simuladores.addMouseListener(new java.awt.event.MouseAdapter() {
            
                
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    Tools.SetImageLabel(simuladores, ruta, new Dimension(400,350));
               
                }
                //Cuando salga el cursor que las miniauturas vuelvan a sus dimensiones normales
                public void mouseExited(java.awt.event.MouseEvent evt) {
                
                    Tools.SetImageLabel(simuladores, ruta, new Dimension(381,291));
                    
                }
                //Para detectar el click
                public void mouseClicked(java.awt.event.MouseEvent evt){
                    padre.cargarJuego(indexJuego);
                }
                
            });
                         
        }
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grado0 = new javax.swing.JLabel();
        grado1 = new javax.swing.JLabel();
        grado2 = new javax.swing.JLabel();
        grado3 = new javax.swing.JLabel();
        grado4 = new javax.swing.JLabel();
        grado5 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setOpaque(false);
        setLayout(new java.awt.GridLayout(2, 3));

        grado0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(grado0);

        grado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(grado1);

        grado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(grado2);

        grado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(grado3);

        grado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(grado4);

        grado5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(grado5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grado0;
    private javax.swing.JLabel grado1;
    private javax.swing.JLabel grado2;
    private javax.swing.JLabel grado3;
    private javax.swing.JLabel grado4;
    private javax.swing.JLabel grado5;
    // End of variables declaration//GEN-END:variables
}
